# Generated by Django 2.2.6 on 2019-11-24 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0002_auto_20191124_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aliment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_api.Aliment')),
            ],
        ),
        migrations.AlterField(
            model_name='food',
            name='aliment',
            field=models.ManyToManyField(through='my_api.Step', to='my_api.Aliment'),
        ),
        migrations.AddField(
            model_name='step',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_api.Food'),
        ),
    ]
