# Generated by Django 2.2.6 on 2019-11-24 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0007_auto_20191124_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='aliment',
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Step',
        ),
    ]
